apiVersion: v1
kind: Namespace
metadata:
  name: guestlist-dev
  labels:
    name: guestlist-dev
    environment: dev
    app: guestlist
    managed-by: terraform
  annotations:
    description: "Guest List application namespace for development environment"
