on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to run"
        required: true
        type: choice
        options: [ validate, plan, apply-dev, destroy ]
      environment:
        description: "Target environment (for apply/destroy)"
        required: false
        default: dev
        type: choice
        options: [ dev, staging, main, dvir-feature ]

  pull_request:
    branches: [ "*-feature", "dev", "staging", "main", "dvir-feature" ]
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.yml"
      - "**.yaml"

  push:
    branches: [ main, dev, dvir-feature ]
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.yml"
      - "**.yaml"
    paths-ignore:
      - ".github/workflows/**"
