name: Terraform • Main Controller

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to run"
        required: true
        type: choice
        options: [ validate, plan, apply-dev, destroy ]
      environment:
        description: "Target environment (for apply/destroy)"
        required: false
        default: dev
        type: choice
        options: [ dev, staging, main, dvir-feature ]

jobs:
  call-validate:
    if: ${{ github.event.inputs.action == 'validate' }}
    uses: ./.github/workflows/tf-validate.yml

  call-plan:
    if: ${{ github.event.inputs.action == 'plan' }}
    uses: ./.github/workflows/tf-plan.yml

  call-apply:
    if: ${{ github.event.inputs.action == 'apply-dev' }}
    uses: ./.github/workflows/tf-apply-dev.yml

  call-destroy:
    if: ${{ github.event.inputs.action == 'destroy' }}
    uses: ./.github/workflows/tf-destroy.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      confirm: destroy ${{ github.event.inputs.environment }}
