name: Terraform • Validate

on:
  workflow_call:
  push:
    branches: [ main ]
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.yml"
      - "**.yaml"
      - ".github/workflows/**"
  pull_request:
    branches: [ "*-feature", "dev", "staging", "main" ]
    paths:
      - "**.tf"
      - "**.tfvars"
      - "**.yml"
      - "**.yaml"
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Terraform fmt (check)
        run: terraform fmt -check -recursive

      - name: Terraform init (no backend)
        run: terraform init -backend=false

      - name: Terraform validate
        run: terraform validate
